#!/bin/bash

tests=(	"0+#-' " 	"111111"
	" "		 	"000001"
	"#0 ##" 	"101001"
	"0+-ri" 	"110100"	
	"0+-10.10" 	"110100"
	"0+-010.10" 	"110100"
)

function cmp
{
	eval $red; echo "GROS TEST $3" 
	if [ -n $3 ] ; then
	    diff <(eval $1) <(echo -n $2)
	fi
}

for i in $(seq 0 2 $((${#tests[@]} - 1))); do
	cmp "../parser \"${tests[$i]}\"" ${tests[$(($i + 1))]} $i
done

