#!/bin/bash

cmd=../../$(basename $(dirname $(pwd)))
fichiers=$(ls test_*)
function cmp {
	echo `eval $1`
	diff <(eval $1) <(eval $2)
}

test_description='OSEF'
. sharness.sh

i=0
for fichier in $fichiers ; do
	while IFS='' read -r line || [[ -n "$line" ]]; do
		$fichier "test $i" " 
			cmp '$cmd $line' 'printf $line %d'
		"
		let "i++"
	done < ../$fichier
done
	
test_done	
