SRCS = ft_putchar.c, ft_putstr.c, ft_strcmp, ft_strlen, ft_swap
SRC_DIR = srcs/
INCLUDES = includes/
TARGET = libft.a

all:
	ar $(SRCS) $(TARGET)

clean:
	rm *o

fclean: clean
	rm $(TARGET)

re: fclean
	make all
