    void cast();
    void	choose_itoa(char type, void *val, size_t *c);
    void	create_arg(void *value, char type, int padding, int precision, int alternate, int sign);
    void		itoa_base_dioux(unsigned int i, size_t base, size_t *c);
    void		itoa_base_l(long int i, size_t base, size_t *c);
    void		itoa_base_ll(long long int i, size_t base, size_t *c);
    int main(int argc, char **argv);
    void	print_arg(t_num *num);
    void	print_padding(size_t count, char with, size_t *c);
    void	print_sign(int sign, size_t *c);
    void	print_value(void *val, char type, size_t *c, size_t precision);
